apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "save-the-elephant.fullname" . }}-postgresql-config
  labels:
    {{- include "save-the-elephant.labels" . | nindent 4 }}
data:
  postgresql.conf: |
    # Connection Settings
    max_connections = {{ .Values.postgresql.config.maxConnections }}

    # Memory Settings
    shared_buffers = {{ .Values.postgresql.config.sharedBuffers }}
    effective_cache_size = {{ .Values.postgresql.config.effectiveCacheSize }}

    # WAL Settings
    wal_level = {{ .Values.postgresql.config.walLevel }}
    {{- if .Values.replication.enabled }}
    max_wal_senders = {{ .Values.postgresql.config.maxWalSenders }}
    wal_keep_size = {{ .Values.postgresql.config.walKeepSize }}
    hot_standby = on
    {{- if ne .Values.replication.synchronousCommit "off" }}
    synchronous_commit = {{ .Values.replication.synchronousCommit }}
    synchronous_standby_names = '*'
    {{- end }}
    {{- end }}

    # Logging
    log_timezone = 'UTC'
    log_statement = 'all'
    log_duration = on
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

    # Locale
    datestyle = 'iso, mdy'
    timezone = 'UTC'
    lc_messages = 'en_US.utf8'
    lc_monetary = 'en_US.utf8'
    lc_numeric = 'en_US.utf8'
    lc_time = 'en_US.utf8'
    default_text_search_config = 'pg_catalog.english'
