{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "save-the-elephant.fullname" . }}-backup
  labels:
    {{- include "save-the-elephant.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.backup.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.backup.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        {{- include "save-the-elephant.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backup
    spec:
      ttlSecondsAfterFinished: {{ .Values.backup.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            {{- include "save-the-elephant.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: backup
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ include "save-the-elephant.serviceAccountName" . }}
          restartPolicy: OnFailure
          {{- $pgMajorVersion := regexFind "^[0-9]+" .Values.postgresql.image.tag }}
          containers:
            {{- if .Values.backup.databases }}
            {{- range .Values.backup.databases }}
            - name: backup-{{ . | lower | replace "_" "-" | replace "." "-" }}
              image: "{{ $.Values.backup.image.repository }}:{{ $.Values.backup.image.tag | default $pgMajorVersion }}"
              imagePullPolicy: {{ $.Values.backup.image.pullPolicy }}
              env:
                {{- include "save-the-elephant.backupContainerEnv" $ | nindent 16 }}
                - name: POSTGRES_DATABASE
                  value: {{ . | quote }}
              resources:
                {{- toYaml $.Values.backup.resources | nindent 16 }}
            {{- end }}
            {{- else }}
            - name: backup
              image: "{{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag | default $pgMajorVersion }}"
              imagePullPolicy: {{ .Values.backup.image.pullPolicy }}
              env:
                {{- include "save-the-elephant.backupContainerEnv" . | nindent 16 }}
                - name: POSTGRES_DATABASE
                  value: {{ .Values.backup.database | default .Values.postgresql.auth.database | quote }}
              resources:
                {{- toYaml .Values.backup.resources | nindent 16 }}
            {{- end }}
{{- end }}
