{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "save-the-elephant.fullname" . }}-postgresql
  labels:
    {{- include "save-the-elephant.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | default (randAlphaNum 16) | b64enc | quote }}
  {{- if .Values.replication.enabled }}
  replication-password: {{ .Values.postgresql.auth.replicationPassword | default (randAlphaNum 16) | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.backup.enabled (not .Values.backup.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "save-the-elephant.fullname" . }}-s3
  labels:
    {{- include "save-the-elephant.labels" . | nindent 4 }}
type: Opaque
data:
  access-key-id: {{ .Values.backup.s3.accessKeyId | b64enc | quote }}
  secret-access-key: {{ .Values.backup.s3.secretAccessKey | b64enc | quote }}
  {{- if .Values.backup.s3.endpoint }}
  endpoint: {{ .Values.backup.s3.endpoint | b64enc | quote }}
  {{- end }}
{{- end }}
