name: Release Charts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .  # Look for charts in the root directory (finds save-the-elephant/)
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Update README on gh-pages
        run: |
          # Fetch the gh-pages branch
          git fetch origin gh-pages:gh-pages

          # Checkout gh-pages branch
          git checkout gh-pages

          # Copy README.md from main branch (current tag should be on main)
          git checkout ${{ github.ref_name }} -- README.md

          # Check if there are changes
          if git diff --quiet HEAD -- README.md; then
            echo "No changes to README.md"
          else
            # Commit and push the changes
            git add README.md
            git commit -m "Update README.md from release ${{ github.ref_name }}"
            git push origin gh-pages
            echo "README.md updated on gh-pages"
          fi

          # Go back to the original branch/tag
          git checkout -